function C = C_scara(L2,L3,dq1,dq2,m2,m3,m4,q2)
%C_scara
%    C = C_scara(L2,L3,DQ1,DQ2,M2,M3,M4,Q2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    12-May-2025 19:03:10

t2 = sin(q2);
t3 = m3.*2.0;
t4 = m4.*2.0;
t5 = m2+t3+t4;
C = [L2.*L3.*dq2.*t2.*t5.*(dq1.*2.0+dq2).*(-1.0./2.0);(L2.*L3.*dq1.^2.*t2.*t5)./2.0;0.0;0.0];
end
