function G = G_scara(m3,m4)
%G_scara
%    G = G_scara(M3,M4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    12-May-2025 19:03:10

G = [0.0;0.0;m3.*(9.81e+2./2.0e+2)+m4.*(9.81e+2./1.0e+2);0.0];
end
