function M = M_scara(Izz1,Izz2,Izz4,L2,L3,m1,m2,m3,m4,q2)
%M_scara
%    M = M_scara(Izz1,Izz2,Izz4,L2,L3,M1,M2,M3,M4,Q2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    12-May-2025 19:03:09

t2 = cos(q2);
t3 = L2.^2;
t4 = L3.^2;
t5 = m3.*t4;
t6 = m4.*t4;
t7 = L2.*L3.*m3.*t2;
t8 = L2.*L3.*m4.*t2;
t9 = (m2.*t4)./4.0;
t10 = (L2.*L3.*m2.*t2)./2.0;
t11 = Izz2+Izz4+t5+t6+t7+t8+t9+t10;
M = reshape([Izz1+Izz2+Izz4+t5+t6+t7.*2.0+t8.*2.0+t9+(m1.*t3)./4.0+m2.*t3+m3.*t3+m4.*t3+L2.*L3.*m2.*t2,t11,0.0,Izz4,t11,Izz2+Izz4+t5+t6+t9,0.0,Izz4,0.0,0.0,m3./4.0+m4,0.0,Izz4,Izz4,0.0,Izz4],[4,4]);
end
